#!/bin/bash
#~~Teste err
if ! ( ls $1/ > '/dev/null' );then
	Sinb_err; echo -en " no diretorio \e[1;37m$1\e[0m"; exit; fi

function pre_install {
	SIG whi ".." "Será necessário instalar $1"
	if continuo; then
		if ! (sudo apt install "$1");then
			SIG err "ERRO" "na instalação de $1"
			exit 1
		fi
	else
		exit 1
	fi
}
function pre_teste {
	if ! ( which "$1");then
		pre_install "$1"
	fi
}
