#!/bin/bash
function teste_app(){
	if [ ! -x "$(command -v "$1")" ]; then
        	mensagem="\e[1;32m[\e[0m\e[1;33m-\e[0m\e[1;32m]\e[0m\e[1;38m "$1"\e[0m required to run script"
        	exit 1
	fi
}
function caso_erros(){
	echo "error: "+ $var_de_erro
	usage_menu
	exit
}
function usage_menu(){
	echo "USAGE: [IP] [OPTIONS]"
	echo "EX: \e[1;32m http://\e[0m 10.10.1.10\e[1;32m / \e[0m -a"
	echo -e "OPTIONS:
		-a:	amass
		-s:	assetfinder
		-u:	sublist3r
		-d:	dirb
		-i:	dirbuster&
		-f:	ffuf
		-g:	gobuster
		-h:	SHOW OPTIONS again"
}
function testar_entraga_variavel(){
	mensagem='OK'
	if [ $1 -lt 2 ];then 		mensagem='Erro de Entrada';fi
	echo $mensagem
}
function acao(){ # $1-$caminho_diretorio $2-nome $3-comando
		dir_e_name="$1""/""$2"".txt"
		if [ ! -f "$dir_e_name" ];then touch "$dir_e_name";fi
		chmod 777 "$dir_e_name"
		echo -e "\e[1;32m[\e[0m\e[1;33m-\e[0m\e[1;32m]\e[0m Processando \e[1;33m $2\e[0m..." 
		($3) > "$dir_e_name"
		gerados[j]="$dir_e_name"
		j=${#gerados[@]}+1
		echo -ne "    \e[1;33m$2\e[0m Fianlizado.\n    Exibir (y/n)?"
		read -n1 opsao
			echo -e "\n"; #sleep 1;
			tput cuu1;tput dl1;
			tput cuu1;tput dl1;
			tput cuu1;tput dl1;
			tput cuu1;tput dl1;
			tput cuu1;tput dl1;
		echo -e "\e[1;32m[\e[0m\e[1;34m+\e[0m\e[1;32m]\e[0m \e[1;33m$2\e[0m Fianlizado."
		# Print Result ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		if [[ $opsao = "y" || $opsao = "Y" ]]
		then 
			echo -e "    \e[1;32m[\e[0m\e[1;36m>\e[0m\e[1;32m]\e[0m \e[1;33m $2\e[0m Results:\n "
			cat "$dir_e_name"
		fi
}
# Ambiente    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
num_arg=$#
url=$1
toda_linha=$@
argumentos=${toda_linha#"$url"}
so_argumentos=${argumentos// -/}
url_no_http="${url#http://}"
url_no_https="${url_no_http#https://}"
caminho_diretorio="${url_no_https//:/.}""/1.Information_Gathering"
var_de_erro=$(testar_entraga_variavel $#)
if [[ $var_de_erro != 'OK' ]];then	echo "Erro:" $var_de_erro;usage_menu;exit;fi
	#cria diretorios
if [ ! -d "${url_no_https//:/.}" ];then	mkdir "${url_no_https//:/.}";fi
chmod 777 "${url_no_https//:/.}"
if [ ! -d "$caminho_diretorio" ];then mkdir "$caminho_diretorio";fi
chmod 777 "$caminho_diretorio"
#Execuçao dos comandos
		i=0;j=0
		while [ $i != ${#so_argumentos} ]
		do
			case ${so_argumentos:$i:1} in 
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		"g") #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Processar -g:	gobuster 
			teste_app "gobuster"
			comando="gobuster dir -q -u $url -w /usr/share/wordlists/dirb/common.txt"
			acao "$caminho_diretorio" "GoBuster" "$comando"
;;
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		"f") #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Processar -f:	ffuf 
			teste_app "ffuf"
			url_go="$url/FUZZ"
			comando="ffuf -s -v -u $url_go -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt:FUZZ"
			acao "$caminho_diretorio" "Ffuf" "$comando"
;;
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		"d") #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Processar -d:	dirb			
			teste_app "dirb"
			comando="dirb $url -w -S"
			acao "$caminho_diretorio" "Dirb" "$comando"
;;
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		"s") #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Processar -s:	assetfinder
			teste_app "assetfinder"
			comando="assetfinder $url_no_https"
			acao "$caminho_diretorio" "AssetFinder"".txt" "$comando"
			revisar="$caminho_diretorio""/AssetFinder"
			cat "$revisar"".txt"  | wc -l  >> "$revisar""-filtrado.txt" 
			gerados[j]="$revisar""-filtrado.txt"
			j=${#gerados[@]}+1
			comando="assetfinder --subs-only $url_go"
			acao "$caminho_diretorio" "AssetFinder-subs-only"".txt" "$comando"
			revisar="$caminho_diretorio""/AssetFinder-subs-only"
			cat "$revisar"".txt"  | wc -l  >> "$revisar""-subs-filtrado.txt" 
			gerados[j]="$revisar""-subs-filtrado.txt" 
			j=${#gerados[@]}+1
			cat "$revisar""-filtrado.txt" | grep $url >> "$revisar""-subs-url-filtrado.txt"
			gerados[j]="$revisar""-subs-url-filtrado.txt" 
			j=${#gerados[@]}+1
;;
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		"a") #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Processar -s:	amass
			comando="amass enum -d $url"
			acao "$caminho_diretorio" "Amass"".txt" "$comando"
			revisar="$caminho_diretorio""/Amass"
			sort -u $revisar".txt" >> $revisar"-filtrado.txt"
			gerados[j]="$revisar""-filtrado.txt" 
			j=${#gerados[@]}+1
;;
		"u")
			echo "#Sublist3r - Nao configurado"

;;
		"i")
			echo "i" "dirbuster& - Nao configurado"
;;
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		"h") #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Help
			usage_menu
			exit
;;
		esac

		i=$(($i+1))
		done
if [ -n "${gerados[*]}" ];then
		echo -e "\n\e[1;32m[\e[0m\e[1;35m*\e[0m\e[1;32m]\e[0m \e[1;35m Arquivos Gerados: \e[0m"
		for arquivo in "${gerados[@]}"
		do
    	echo -e " $arquivo"
    done
fi
